<?php
$SETTINGS['settings_file'] = 'settings/settings.inc.php';
$SETTINGS['files_file'] = 'settings/files.inc.php';
$SETTINGS['script'] = '/phpSitemapNG/index.php';
$SETTINGS['debug'] = '';
$SETTINGS['state'] = 'getSettings';
$SETTINGS['executed'][''] = '1';
$SETTINGS['executed']['getSettings'] = '1';
$SETTINGS['timeout_automatic'] = '';
$SETTINGS['page_root'] = '/home/content/c/a/r/caryweb/html/';
$SETTINGS['website'] = 'http://www.aqxpkzuvzq.com/';
$SETTINGS['crawler_url'] = 'http://www.aqxpkzuvzq.com/';
$SETTINGS['sitemap_file'] = '/sitemap.xml';
$SETTINGS['txtsitemap_file'] = 'itpimdbszdpodsfuf, <a href=\"http://www.drjlamoobh.com\">axzoyovwqa</a> ';
$SETTINGS['temp_dir'] = '/home/content/c/a/r/caryweb/html/phpSitemapNG/inc/functions/temp/';
$SETTINGS['public_url'] = '/home/content/c/a/r/caryweb/html/phpsitemapng.php';
$SETTINGS['scan_local'] = '1';
$SETTINGS['scan_website'] = '1';
$SETTINGS['ping_google'] = '1';
$SETTINGS['edit_result'] = 'edit_result_TRUE';
$SETTINGS['store_filelist'] = 'TRUE';
$SETTINGS['timeout'] = 'timeout_force';
$SETTINGS['timeout_duration'] = '30';
$SETTINGS['disallow_dir']['0'] = 'itpimdbszdpodsfuf, <a href=\"http://www.drjlamoobh.com\">axzoyovwqa</a>';
$SETTINGS['disallow_file']['0'] = 'itpimdbszdpodsfuf, <a href=\"http://www.drjlamoobh.com\">axzoyovwqa</a>';
$SETTINGS['disallow_key']['0'] = 'itpimdbszdpodsfuf, <a href=\"http://www.drjlamoobh.com\">axzoyovwqa</a>';
$SETTINGS['changefreq'] = 'changefreq_dynamic';
$SETTINGS['changefreq_fixed'] = 'always';
$SETTINGS['priority'] = 'priority_fixed';
$SETTINGS['priority_fixed'] = '0.0';
$SETTINGS['lastmod'] = 'lastmod_filedate';
$SETTINGS['lastmod_format'] = 'short';
$SETTINGS['compress_sitemap'] = '';
$SETTINGS['sitemap_url'] = '/sitemap.xml';
$SETTINGS['scan_website_level'] = '0';
$SETTINGS['timeout_is'] = '';
$SETTINGS['timeout_time'] = '1352575961.9935';
$SETTINGS['timeout_shutdown'] = '3';
$SETTINGS['timeout_deadline'] = '1352575988.9935';
?>
