<?php
$descriptions = array(
"arch" => "
<p>Architectural Precast Concrete is made in a manufacturing facility by mixing cement, aggregate and color as required and placing the mixture into a form. The concrete is usually reinforced with steel to increase strength, especially is shear or tension (concrete is inherently strong in compression). Once the mixture has begun to cure (usually 16-24 hours), the piece is removed from the form. Then, exposed faces are usually finished by sandblasting, acid washing or other means.</p>

<p>Precast concrete pieces come in a variety of colors and finishes. Custom forms can be built, thereby allowing for an unlimited design capability with the product. The economics of architectural precast concrete are most favorable when many pieces can be poured from the same form.</p>

<p>Connections can be as versatile as the pieces themselves. Steel or other connection hardware can be embedded in the concrete, and bolted or welded to the supporting structure. The pieces themselves can act as structural elements.</p>

<p>Architectural precast concrete may also have other face materials embedded in it, covering all or most of the face. Stone-clad and brick-clad precast are increasingly common. Plant labor is much more efficient than jobsite labor and so cost savings can be significant.</p>

<p>Detailed information on this material can be found at: <a href=\"http://www.pci.org\" target=\"_new\">www.pci.org</a> and at <a href=\"http://www.archprecast.org\" target=\"_new\">www.archprecast.org</a>. Both sites have excellent and extensive pictures of various colors and finishes.</p>",

"cstone" => "
<p>\"Cast stone\" can be confusing because so many different products use this label, resulting in multiple meanings. Cement, concrete, and stone have always been related, both chemically and linguistically. Cement, which is the \"glue\" or binder in concrete, is manufacturing by grinding and heating limestone and other ingredients. Modern cements are called \"Portland cement\". \"Portland\" is a reference to the Isle of Portland in Britain. Early British cements (19th century) were named \"Portland\" because of the similarity in color and appearance of the cement and resulting concrete to the limestone cliffs of Portland.</p>

<p>The term \"cast stone\" itself has a clear plain meaning, a manufactured product that was cast or molded and has a stone-like appearance. Given the wide variations in color, texture, and overall surface appearance of stone this covers a lot of ground. The term \"cast stone\" is useful to manufacturers and their trade associations because it sounds better than \"stone-like concrete\" or any other alternative. It is desirable from a marketing perspective primarily because it evokes stone rather than concrete or other less desirable materials. Thus, it is understandable that so many products lay claim to the term. However, this makes it confusing to specifiers and buyers alike unless they are very well versed in the subtle differences among all the products that describe themselves, or are described by others, as cast stone.</p>

<p>The most common use of \"cast stone\" is to describe a form of precast concrete made of portland cement, sands, and aggregates and having excellent physical characteristics and an appearance similar to cut stone, usually smooth honed limestone. It is distinguished from other forms of precast concrete by its stone-like appearance and the absence of surface voids or \"bugholes\". There is no difference between bughole free architectural precast concrete and cast stone. Cast stone is a specific type of architectural precast. It may be manufactured by the dry-tamp or wet-cast process. Both produce handsome, durable material. Generally the dry-tamped material has a slightly finer finish and the wet-cast more flexibility of connections and sizes. The Cast Stone Institute, a trade association, makes no distinction between the two manufacturing methods. Few people outside the cast stone industry can tell the difference. In fact, most construction professionals cannot reliably tell the difference between natural stone and cast stone, particularly if the viewing distance is more than a few feet. That is the basis of cast stone's appeal: it is virtually indistinguishable from stone, has more flexibility, and often costs less.</p>

<p>Unlike other forms of concrete, there is only one finish available in cast stone: stone. Sometimes, particularly in the context of wet-cast cast stone, this will be referred to as \"acid wash\" (because of the use of acid to remove the very outer skin of cement paste, exposing a tiny bit of sand texture and removing the gloss associated with wet concrete formed against the very smooth surfaces of high quality forms). It is also occasionally referred to as \"sugar cube\" for obvious reasons. A very light sandblast will produce a similar finish, though today acid washing is the preferred method for creating a cast stone finish. One reason for this trend is because sandblasting presents more environmental problems for the manufacturer than does acid. Also, sandblasting results in a finish that is slightly duller and is usually less consistent than acid wash (though some manufacturers contend they get more consistency with sandblasting).</p>

<p>Other materials that call themselves \"cast stone\" or are referred to by others that way:

<p><u>Calcium silicate building units:</u> (Renaissance Stone&reg;, manufactured by Arriscraft Corporation) These are machine-made by pressing silica sand and other materials into a mold and then autoclaving (high temperature and pressure) them. There is no portland cement in this product, but the silica sand becomes cementitious. The pieces are designed to work with 3 5/8\" modular brick and are 2' long. They do not typically refer to their product as \"cast stone\" but others may.</p>

<p><u>Thin precast veneer units:</u> (Cultured Stone&reg; is the best-known of many brands.) These are generally small, and the artful use of pigments and of rubber molds taken from real stones gives the pieces the appearance of a variety of stones. Often the shape or texture is that of split or rough stones or of rounded fieldstones and the color is not uniform, closely resembling the color variations in numerous types of stones. They are weak, and incapable of carrying load or of being stacked, and are typically adhered to a backup with \"glue\" (mortar, mastic, or other adhesives) and do not easily integrate with other masonry, such as 3 5/8\" modular brick.</p>

<p><u>Catalog houses with precast:</u> These are precast units, either wet-cast or dry tamped, made and sold by numerous catalog manufacturers. Some include bugholes in their definition of \"cast stone\" and in the product; others provide bug-hole free material. Range of products, finish, and quality, vary from one manufacturer to another.</p>

<p><u>Specialized stone types:</u> Certain natural stones have a surface riddled with holes. Bugholes from production are masked by the irregular surface or incorporated into the intentional voids. Such natural stones are commonly used in areas where the stone is local and these manufacturers duplicate the look well. Typical geographic areas are the Southwest and Florida.</p>

<p><u>Specialized CMU-type products:</u> (Prairie Stone&trade;, manufactured by Northfield Block) This is a machine made product with a ground face finish and a mix optimized to produce a limestone appearance. They do not refer to their product as \"cast stone\" but others may.</p>

<h3>DRY-TAMP CAST STONE</h3>
<p>In the dry-tamp process, a very stiff, or dry (zero-slump) mixture of cement, water, sands, and aggregate are pounded or tamped into the mold. If you've ever hard packed moist sand at the beach into a bucket, then turned it over and noticed how well it keeps its shape, you have witnessed the basis of dry-tamp cast stone. The material can be taken out of the mold immediately, left to cure, and the mold re-used. The piece keeps it shape and moist curing helps the concrete to harden overnight. A very light acid wash is typically used to remove cement film. This is a hand crafted process. The same basic process is used on machines with a different, but related, zero-slump mix in the manufacture of concrete block (Also known as CMU - Concrete Masonry Unit; in the past it was often called \"cinder block\" because of the light-weight, low cost cinders commonly used as aggregate.). Typically dry-tamped cast stone is connected to the structure very much like cut stone, using small stone anchors. Threaded inserts and weld plates can be built into the piece, though there are some limitations on where they may be placed. Handling of larger pieces is with belts and forklifts or with special inserts for standard or coil bolts (bolts with extremely coarse threads designed for use in concrete).</p>

<p>Under certain conditions, dry-tamped cast stone may show crazing - a series of very fine interconnected cracks on the surface. Because the aggregates and the finish are typically finer in dry-tamped cast stone than in other concrete products, crazing is more visible. Care must be taken in detailing to avoid having the unexposed surfaces sit in water or high moisture, as the moisture differentials between the face and other surfaces will promote crazing. For more detail, see the Cast Stone Institute Technical Bulletin #32 on crazing.</p>

<h3>WET-CAST CAST STONE</h3>
<p>The wet-cast process is essentially the same as that employed in most concrete: a flowable mixture of cement, water, sands, and aggregate is poured into a mold and vibrated. The wet concrete stays in the mold until it has attained sufficient strength to be removed; under typical controlled plant conditions this is overnight. After the forms are removed, acid is used to etch the surface, removing a tiny bit of the cement paste and the resulting finish (given that the mix has been optimized to produce a beautiful surface) is very fine and stone-like. Any voids or bugholes get filled through a hand-finishing process called \"rubbing\" or \"sacking\" in which a mixture of portland cement and very fine sand is used to fill the small surface voids. The resultant product has the appearance of stone, with the strength and full flexibility of connection options (embedded plates, adjustable inserts, etc.) of any other precast concrete.</p>

<h3>CAST STONE versus LIMESTONE: Cost Considerations</h3>
<p><u>Overview:</u> Shapes are produced in limestone by a subtractive process - material is removed from a solid block to get the desired shape. Cast stone uses a molded process in which concrete is poured and vibrated in a mold (or, in the case of dry tamp, tamped into the mold). Major determinants of limestone price include gross cross section (area of the rectangular block before tooling/removal of material, and the amount of complex or simple tooling needed to get the desired profile. Cast stone prices reflect the cost of the mold (the number of repetitive uses of the mold on the project will determine how much this affects the unit price), the surface area that is exposed, and to some extent, the net volume or cross sectional area.</p>

<p><u>Cross-Sectional Area:</u> All other factors being equal, the larger the cross-section, the more cast stone will tend to be less costly than limestone. Small, simple cross-sections (less than 32 Sq. In/Lin. Ft are almost never cheaper in cast stone, only above 48 Sq. In/Lin. does area even start to favor cast stone on a cost basis.</p>

<p><u>Repetition:</u> Repetition favors cast stone because the mold costs are amortized over a larger base. Individual pieces with low repetition, for example, 2-4 complex medallions, will almost always be less costly in limestone. The more complex the mold, the more cast stone will require repetition to offset the mold cost. Ramp and twist coping for a short stair wall, where the forms are relatively expensive and changes in radius or rise may necessitate multiple forms, will be less costly in limestone.</p>

<p><u>Shape Factors:</u> Shapes such as overhanging cornices and protruding bullnoses, will add more to the cost of limestone than to cast stone, reflecting both the gross block and the machine/labor time to remove a lot of material.</p>

<p><u>Complexity/Ornateness:</u> This may encompass many distinct factors. With sufficient repetition, complexity will favor cast stone. If dentils are added to a moderately small and simple band, which may be of roughly equivalent cost in limestone and cast stone, the added cost of cutting each dentil will far exceed the added mold costs, and the cast stone will be cheaper.</p>

<p><i>A NOTE ON COLOR:</i> On some projects, color match is a major reason that cast stone is selected. It can be made in many shades. On renovation projects, cast stone will provide a much better match for aged limestone than will new stone. On new projects the wide range of colors may be used either to match another material or to complement or contrast.</p>
",

"frp" => "
<p>This material basically consists of a polymer (all \"plastics\" are made of polymers  long chain molecules) and glass fiber reinforcing. It is called a composite material because its physical properties arise from the combination of two materials with distinctly different properties.  In this regard it is similar to common reinforced concrete. Portland cement concrete (what we usually mean by \"concrete\") consists of a matrix (cement and aggregate) and another material (rebar) to give it strength in directions in which it is not naturally strong; FRP uses a resin for the matrix and glass fibers to give it strengths in the directions in which resin alone is not strong.</p>

<p>FRP is unaffected by freeze-thaw, can be both light and strong, and can take numerous finishes, either integral or plant-applied (such as automotive paint, etc...).  In terms of color and texture, it is very versatile. The typical architectural uses for FRP we are involved with include columns (column covers to be more precise) and cornices (where the light weight allows for a simpler structure than solid concrete or stone), as well as domes, large public art and sculpture, and as a substrate for <a href=\"#mosaic\">mosaics</a>.</p>
",

"gfrg" => "
<p>Glass Fiber Reinforced Gypsum is made by spraying or laminating gypsum and glass fibers into a mold to create architectural pieces. Gypsum is a cementitious material that is the base material of plaster. Our pieces are generally sold with a white surface suitable for field finishing. Paint finishes are typically done in the field. These include scagliola, an ancient technique for producing faux stone.</p>

<p>The addition of polymers increases strength. Then the product becomes known as Polymer Glass reinforced Gypsum (PGRG). This is commonly used in high traffic locations or in exterior applications where is can be protected against standing water.</p>

<p>Numerous suppliers have catalogs with standard parts. Our GRG focus is exclusively on complex, non-standard shapes.</p>
",

"gfrc" => "
<p>GFRC is used extensively in Europe and Asia. The past 5-10 years have seen increasing use of GFRC in commercial construction in the U.S. At its broadest meaning, \"GFRC\" applies to any concrete in which glass fibers are used. It commonly refers to a number of specific and very different types of precast concrete products, typically those in which glass fiber is the only reinforcing (i.e., no rebar). As there is nothing proprietary about the term \"GFRC\" anyone is free to use it, and to use it however they wish. In addition, the term GRC (Glass Reinforced Cement) is also used to describe certain products. The products vary in their characteristics, such as cost, strength, appearance, installation methods, etc. This can lead to some confusion. We explain the main types below.</p>

<p>Over the past 5 years we have noticed an increased use of GFRC and frequent misunderstanding by designers and specifiers of its nature and variants. The confusion is understandable, as architects have to deal with 1000's of products and cannot know the intricacies of each. Nevertheless, conflicts among and between drawings, specs, and intent cause confusion for contractors. We hope the brief explanations below can be of use.</p>

<p><u>Spray-chop panels:</u> (Typically called GFRC) This is a thin material (typically between 3/8\" and 7/8\" thick) produced by spraying a mixture of sand, cement, and glass fibers into a mold and, while still wet, attaching a light-gauge steel frame to the panel. The production apparatus chops fibers and introduces them into the mix stream being sprayed, hence the term \"spray-chop\". The skin and frame form a strong, thin, lightweight panel. Attachment to the building structure is made to the frame, using welding or bolting. Like most panels, gravity and wind loads are transferred from each panel to the structure at only a few points The most common finish is a light sandblast, resulting in a stone-like surface. Combinations of aggregates and pigments are used to produce colors, most typically relatively subdued earth tones. They can also be painted.</p>

<p><u>Pre-mix GFRC:</u> In this process, the fibers are mixed in with the sand and cement and the mixture is then compacted into molds by any of various processes. Typical thicknesses are 1\"-2\", but this process is also used to make solid blocks.  This process is typically used for smaller pieces. It is also used to emulate terra cotta. Pieces can have the same shape, (webs, etc.) as terra cotta. This type of GFRC is not typically used for large pieces and never for large panels. Fabricators rarely participate in any certification program, and so quality varies. Doing homework on the fabricator is recommended. For many reasons we think the plant we use for this material is one of the best.</p>

<p><u>Thin hand-troweled:</u> (most usually called GRC, Glass Reinforced Cement) In this process, a cement and glass fiber mix is troweled or laminated into a mold. Column covers, a common application, will have thickness in the 1/8\"-5/16\" range. There is no frame. Attachment is by screwing through the material and patching the holes. There are no manufacturer-supplied finishes or, in most instances, color. This product is called \"paint ready\" and is designed to receive a coating in the field. Manufacturing quality varies, as there is no certification program. GRC is substantially lower in cost and strength and strength than GFRC. Substitution of GRC for GFRC is often attempted. In some instances it may be appropriate; in other instances it causes problems. Specifiers should be clear on what they want and communicate their intent clearly and crisply.</p>

<p>&bull; <i>NOTE ON FIBERS</i>:
<br>Fibers other than glass (steel, polypropylene, nylon, and other materials) are used in many types of concrete for a number of purposes. In most instances there is conventional steel reinforcement and these fibers are secondary reinforcement. In some flat work and other non-structural applications, such fibers may the only reinforcement. Glass fibers impart unusual strength. GFRC always uses special alkali-resistant glass fibers as over time the highly alkaline environment within concrete will weaken ordinary glass fibers.</p>

<p>&bull; <i>NOTE ON INTERNATIONAL USAGE: GRC vs. GFRC</i>
<br>In Europe, especially the UK, GRC is the more common term and applies to panels that in the US we would call GFRC. This is yet another source of confusion, especially notable when using internet searches.</p>",

"mosaic" => "
<p>Mosaics are an ancient art in which small colored pieces of tile (stone, glass, ceramics, etc.) are arranged to create a design. The design can be representational or abstract. The tiles can cover virtually any type of surface, such as floors, walls, park benches. \"Stained glass\" is used in two ways: to refer to various types of colored or stained glass, and to refer to art works (such as church windows) made by joining together pieces of colored glass.  The latter is one type of mosaic, and colored glass is often used in mosaics that are not translucent.  In stained glass, typically the entire piece transmits light except for the lead cames often used to join the pieces of together into an assemblage.  Most other mosaics have grout between the pieces.</p>

<p>We are interested in mosaics from a few different perspectives (in addition to marveling at how wonderful many of them are) and welcome inquiries about any of the following:</p>

<p>&bull; Precast concrete as a formed surface on which a mosaic can be applied.  This makes sense (in comparison to cast-in-place concrete) only if there is repetition or if the placement of the shape makes forming cast-in-place exceptionally difficult.  I have reviewed potential projects and often recommended cast-in-place as the most appropriate approach.</p>

<p>&bull; Large scale mosaics plant-cast into a precast panel.  We are very interested in employing mosaics in commercial construction as well as in the public art context.</p>

<p>&bull; Fiberglass as a formed surface on which a mosaic can be applied.  If the fiberglass is translucent this allows a design to look like a traditional reflective mosaic in daylight (i.e. when lit from the front) and like a stained glass window at night (when lit from the back or inside). </p>

<p>Please contact us if you have interest in any of these areas.</p>
",

"tcotta" => "
<p>Terra Cotta is a molded clay product that has been in use for thousands of years. The pieces can be glazed or unglazed, in a wide variety of colors. Glazes are decorative, and not required for durability. One piece can have several color schemes. Terra cotta pieces can be very detailed, and have been used to ornament a variety of buildings. The pieces can be continuous, such as banding or fascia or, individual pieces such as brackets, pier caps, or statues.</p>

<p>Terra Cotta is a combination of clay, previously fired clay, called \"grog\", and additives. The mixture may be extruded or pressed into a wood or plaster mold, then removed and heated in a kiln. Some pieces with a constant cross section can be extruded. Glazes get a separate firing. The color range is extraordinary and the colors do not fade. The final product has an impervious surface, which can be used in exterior and interior applications.</p>

<p>Connection of the terra cotta to the support structure is generally done with stainless steel pins and straps which are screwed to the back up structure. Many years ago, terra cotta connections were done with plain steel, which now, years later, are corroding in some instances. This is not a problem with the actual terra cotta material, but with the installation methods used years ago.</p>

<p>In certain situations damaged terra cotta may be replaced with GFRC or FRP. We are providers of these substitute materials . Both these materials may have integral or applied finishes to simulate glazed terra cotta. Both are more economical than terra cotta and generally have shorter lead times, as a piece of glazed terra cotta cannot typically be produced in less than 40-45 days; lead times are usually much longer. Because terra cotta shrinks significantly during the drying and firing cycles that lead to its chemical transformation into a hard durable material, molds are oversized. Thus molds for replacement parts must be constructed; with GFRC or FRP, molds can be taken directly from existing pieces, reducing costs and shortening lead times.</p>
");